"""URL configuration for agents_app dashboard."""
from django.urls import path
from .views_dashboard import (
    agents_list,
    create_first_agent,
    agent_create,
    agent_detail,
    agent_edit,
    agent_train,
    validate_connector_ajax,
    toggle_tool_ajax,
    agent_test,
    agent_webhook_test,
    agent_publish,
    regenerate_api_key,
    add_agent_api_key,
    revoke_agent_api_key,
    sync_models,
    optimize_agent,
    update_agent_model,
    upload_chat_file,
    agent_delete,
    mcp_server_create,
    mcp_server_update,
    mcp_server_toggle,
    mcp_server_delete,
    user_profile,
    generate_api_key,
    revoke_api_key,
    training_data_detail,
    share_agent,
    accept_agent_share,
    resend_agent_share_email,
    withdraw_agent_share,
    generate_public_share_url,
    deactivate_public_share,
    access_public_share,
    public_agents_list,
    submit_agent_like,
    social_media_oauth,
    get_user_conversations
)
from .views_analytics import (
    analytics_dashboard,
    shared_agent_usage_analytics,
    my_shared_agents_usage
)

urlpatterns = [
    path('', agents_list, name='agents_list'),
    path('create-first-agent/', create_first_agent, name='create_first_agent'),
    path('create/', agent_create, name='agent_create'),
    
    # Static URL paths MUST come before the catch-all <slug:slug>/ pattern
    path('connectors/<int:connector_id>/validate/', validate_connector_ajax, name='validate_connector_ajax'),
    path('<slug:slug>/toggle-tool/', toggle_tool_ajax, name='toggle_tool_ajax'),
    path('share/accept/<str:token>/', accept_agent_share, name='accept_agent_share'),
    path('share/<int:share_id>/resend/', resend_agent_share_email, name='resend_agent_share_email'),
    path('share/<int:share_id>/withdraw/', withdraw_agent_share, name='withdraw_agent_share'),
    path('public/<str:token>/', access_public_share, name='access_public_share'),
    path('public-agents/', public_agents_list, name='public_agents_list'),
    path('public-agents/<slug:slug>/like/', submit_agent_like, name='submit_agent_like'),
    path('public-agents/<slug:slug>/publish/<str:platform>/', social_media_oauth, name='social_media_oauth'),
    path('sync-models/', sync_models, name='models-sync'),
    path('profile/', user_profile, name='user_profile'),
    path('profile/generate-api-key/', generate_api_key, name='generate_api_key'),
    path('profile/revoke-api-key/', revoke_api_key, name='revoke_api_key'),
    path('analytics/', analytics_dashboard, name='analytics_dashboard'),
    path('analytics/shared-usage/', shared_agent_usage_analytics, name='shared_agent_usage_analytics'),
    path('analytics/shared-usage/<slug:slug>/', shared_agent_usage_analytics, name='shared_agent_usage_analytics_agent'),
    path('analytics/my-shared-usage/', my_shared_agents_usage, name='my_shared_agents_usage'),
    path('user/<int:user_id>/conversations/', get_user_conversations, name='get_user_conversations'),
    
    # Agent pages use slug-based URLs - these catch-all patterns MUST come LAST
    path('<slug:slug>/api-keys/add/', add_agent_api_key, name='add_agent_api_key'),
    path('<slug:slug>/api-keys/<int:key_id>/revoke/', revoke_agent_api_key, name='revoke_agent_api_key'),
    path('<slug:slug>/', agent_detail, name='agent_detail'),
    path('<slug:slug>/edit/', agent_edit, name='agent_edit'),
    path('<slug:slug>/train/', agent_train, name='agent_train'),
    path('<slug:slug>/toggle-tool/', toggle_tool_ajax, name='toggle_tool_ajax'),
    path('<slug:slug>/training-data/<int:training_data_id>/', training_data_detail, name='training_data_detail'),
    path('<slug:slug>/test/webhook/', agent_webhook_test, name='agent_webhook_test'),
    path('<slug:slug>/test/', agent_test, name='agent_test'),
    path('<slug:slug>/publish/', agent_publish, name='agent_publish'),
    path('<slug:slug>/regenerate-key/', regenerate_api_key, name='regenerate_api_key'),
    path('<slug:slug>/optimize/', optimize_agent, name='optimize_agent'),
    path('<slug:slug>/update-model/', update_agent_model, name='update_agent_model'),
    path('<slug:slug>/upload-chat-file/', upload_chat_file, name='upload_chat_file'),
    path('<slug:slug>/delete/', agent_delete, name='agent_delete'),
    path('<slug:slug>/mcp-servers/create/', mcp_server_create, name='mcp_server_create'),
    path('<slug:slug>/mcp-servers/<int:mcp_server_id>/update/', mcp_server_update, name='mcp_server_update'),
    path('<slug:slug>/mcp-servers/<int:mcp_server_id>/toggle/', mcp_server_toggle, name='mcp_server_toggle'),
    path('<slug:slug>/mcp-servers/<int:mcp_server_id>/delete/', mcp_server_delete, name='mcp_server_delete'),
    path('<slug:slug>/share/', share_agent, name='share_agent'),
    path('<slug:slug>/public-share/', generate_public_share_url, name='generate_public_share_url'),
    path('<slug:slug>/public-share/deactivate/', deactivate_public_share, name='deactivate_public_share'),
]

