"""
Django settings for oshani project.

Generated by 'django-admin startproject' using Django 4.2.27.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import os

# Load environment variables (optional)
try:
    from dotenv import load_dotenv
    load_dotenv()
except ImportError:
    pass

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# Use environment variable for production - never commit secret keys to version control
SECRET_KEY = os.getenv('DJANGO_SECRET_KEY', 'django-insecure-nj(=rsb+sbbx62okys8liz5i&k&53r*ie%(l2xy=8k^!fg111x')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'False').lower() == 'true'

# Security Headers Configuration
# These work in conjunction with nginx security headers
X_FRAME_OPTIONS = 'SAMEORIGIN'  # Allow embedding in same origin (for admin iframes)
SECURE_CONTENT_TYPE_NOSNIFF = True  # Prevent MIME type sniffing
SECURE_REFERRER_POLICY = 'strict-origin-when-cross-origin'  # Control referrer information
SECURE_CROSS_ORIGIN_OPENER_POLICY = 'same-origin'  # Isolate browsing context

# HTTPS Security (nginx handles SSL termination, but Django should know it's behind HTTPS)
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
# Configurable via env so HTTP-only deployments (e.g. local/IP access without
# TLS) can disable the Secure flag; defaults stay secure for production.
SECURE_SSL_REDIRECT = os.getenv('SECURE_SSL_REDIRECT', 'False') == 'True'  # Nginx handles HTTPS redirect
SESSION_COOKIE_SECURE = os.getenv('SESSION_COOKIE_SECURE', 'True') == 'True'  # Only send session cookie over HTTPS
CSRF_COOKIE_SECURE = os.getenv('CSRF_COOKIE_SECURE', 'True') == 'True'  # Only send CSRF cookie over HTTPS
SESSION_COOKIE_SAMESITE = 'Lax'  # Mitigate CSRF on top-level cross-site requests
CSRF_COOKIE_SAMESITE = 'Lax'

# HSTS: tell browsers to always use HTTPS for this domain (nginx may also set this).
# Enable only when the domain is fully on HTTPS to avoid lockout.
SECURE_HSTS_SECONDS = int(os.getenv('SECURE_HSTS_SECONDS', '31536000'))  # 1 year
SECURE_HSTS_INCLUDE_SUBDOMAINS = os.getenv('SECURE_HSTS_INCLUDE_SUBDOMAINS', 'True') == 'True'
SECURE_HSTS_PRELOAD = os.getenv('SECURE_HSTS_PRELOAD', 'True') == 'True'

# Security: Restrict allowed hosts to prevent host header injection
# In production, set specific domains: ALLOWED_HOSTS = ['yourdomain.com', 'www.yourdomain.com']
# Default hosts include localhost for development and production domains
default_hosts = ['localhost', '127.0.0.1', 'oshaani.com', 'www.oshaani.com', '54.88.28.165']
allowed_hosts_env = os.getenv('ALLOWED_HOSTS', '')
ALLOWED_HOSTS = [host.strip() for host in allowed_hosts_env.split(',') if host.strip()] if allowed_hosts_env else default_hosts


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',
    'django.contrib.humanize',  # For number formatting (intcomma filter)
    'django.contrib.sitemaps',  # For SEO sitemap generation
    'rest_framework',
    'corsheaders',
    'channels',
    'agents_app',
    'connectors',
    'blog_app.apps.BlogAppConfig',
]

MIDDLEWARE = [
    'oshani.middleware.DisallowedHostMiddleware',  # Handle invalid Host headers before SecurityMiddleware
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    # CORS middleware disabled - Nginx handles CORS headers for API routes
    # 'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'oshani.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            BASE_DIR / 'agents_app' / 'templates',
            BASE_DIR.parent / 'frontend' / 'public',  # SPA templates
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'agents_app.context_processors.social_links',
            ],
        },
    },
]

WSGI_APPLICATION = 'oshani.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': os.getenv('DB_NAME', 'oshani'),
        'USER': os.getenv('DB_USER', 'root'),
        'PASSWORD': os.getenv('DB_PASSWORD', ''),
        'HOST': os.getenv('DB_HOST', 'localhost'),
        'PORT': os.getenv('DB_PORT', '3306'),
        'OPTIONS': {
            'charset': 'utf8mb4',
            'init_command': "SET sql_mode='STRICT_TRANS_TABLES'",
        },
    }
}

# Cache configuration (Redis)
# Use django-redis for better Redis integration
try:
    import django_redis
    # Configure Redis cache with optional HiredisParser
    cache_options = {
        'CLIENT_CLASS': f'{django_redis.__name__}.client.DefaultClient',
        'CONNECTION_POOL_KWARGS': {
            'max_connections': 50,
            'retry_on_timeout': True,
        },
    }
    
    # Try to use HiredisParser if available (faster), otherwise use default parser
    try:
        from redis.connection import HiredisParser
        cache_options['PARSER_CLASS'] = f'{HiredisParser.__module__}.HiredisParser'
    except (ImportError, AttributeError):
        # Fallback: don't specify parser, let django-redis use default
        # For newer redis-py versions, parser is auto-selected
        pass
    
    CACHES = {
        'default': {
            'BACKEND': 'django_redis.cache.RedisCache',
            'LOCATION': os.getenv('REDIS_URL', 'redis://localhost:6379/1'),  # Use DB 1 for cache (DB 0 is for Celery)
            'OPTIONS': cache_options,
            'KEY_PREFIX': 'oshani',
            'TIMEOUT': 3600,  # Default timeout: 1 hour
        }
    }
except ImportError:
    # Fallback to basic Redis cache if django-redis is not installed
    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.redis.RedisCache',
            'LOCATION': os.getenv('REDIS_URL', 'redis://localhost:6379/1'),
            'KEY_PREFIX': 'oshani',
            'TIMEOUT': 3600,
        }
    }

# Agent response cache settings
AGENT_RESPONSE_CACHE_ENABLED = os.getenv('AGENT_RESPONSE_CACHE_ENABLED', 'True').lower() == 'true'
AGENT_RESPONSE_CACHE_TIMEOUT = int(os.getenv('AGENT_RESPONSE_CACHE_TIMEOUT', '3600'))  # 1 hour


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Kolkata'  # IST (Indian Standard Time)

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [BASE_DIR / 'agents_app' / 'static']
STATIC_ROOT = BASE_DIR / 'staticfiles'
STORAGES = {
    'default': {
        'BACKEND': 'django.core.files.storage.FileSystemStorage',
    },
    'staticfiles': {
        'BACKEND': 'whitenoise.storage.CompressedStaticFilesStorage',
    },
}

# Media files
MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# REST Framework configuration
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.SessionAuthentication',
        'agents_app.authentication.AgentAPIKeyAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20,
}

# CORS configuration
# Allow requests from SPA on oshaani.pro and local development
CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",
    "http://127.0.0.1:3000",
    "https://oshaani.pro",
    "https://www.oshaani.pro",
]

CORS_ALLOW_CREDENTIALS = True

# CORS headers that can be used
CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
]

# CSRF Trusted Origins
# Required for Django CSRF protection when serving from oshaani.com
# This allows CSRF tokens to work properly for requests from these origins
CSRF_TRUSTED_ORIGINS = [
    'https://oshaani.com',
    'https://www.oshaani.com',
    'https://oshaani.pro',
    'https://www.oshaani.pro',
    'http://localhost:3000',
    'http://127.0.0.1:3000',
]

# Append extra trusted origins from env (comma-separated, full scheme required),
# e.g. CSRF_TRUSTED_ORIGINS=http://1.2.3.4:8000,https://my.domain.com
_extra_csrf_origins = os.getenv('CSRF_TRUSTED_ORIGINS', '')
CSRF_TRUSTED_ORIGINS += [o.strip() for o in _extra_csrf_origins.split(',') if o.strip()]

# AWS Configuration
AWS_ACCESS_KEY_ID = os.getenv('AWS_ACCESS_KEY_ID', '')
AWS_SECRET_ACCESS_KEY = os.getenv('AWS_SECRET_ACCESS_KEY', '')
AWS_REGION = os.getenv('AWS_REGION', 'us-east-1')
# AWS AssumeRole Configuration (for cross-account access)
AWS_ROLE_ARN = os.getenv('AWS_ROLE_ARN', '')  # e.g., 'arn:aws:iam::123456789012:role/SESRole'
AWS_ROLE_EXTERNAL_ID = os.getenv('AWS_ROLE_EXTERNAL_ID', '')  # Optional external ID for role assumption
AWS_ROLE_SESSION_NAME = os.getenv('AWS_ROLE_SESSION_NAME', 'django-ses-session')  # Session name for assumed role
QUICK_SUITE_ACCOUNT_ID = os.getenv('QUICK_SUITE_ACCOUNT_ID', '')

# Amazon Bedrock Configuration
BEDROCK_DEFAULT_MODEL = os.getenv('BEDROCK_DEFAULT_MODEL', 'anthropic.claude-v2')
# Available models:
# - anthropic.claude-v2 (Claude 2)
# - anthropic.claude-v2:1 (Claude 2.1)
# - anthropic.claude-3-sonnet-20240229-v1:0 (Claude 3 Sonnet)
# - anthropic.claude-3-haiku-20240307-v1:0 (Claude 3 Haiku)
# - meta.llama2-13b-chat-v1 (Llama 2 13B)
# - meta.llama2-70b-chat-v1 (Llama 2 70B)
# - ai21.j2-ultra-v1 (Jurassic-2 Ultra)
# - ai21.j2-mid-v1 (Jurassic-2 Mid)

# Amazon Bedrock Video Generation Configuration
# S3 bucket for storing video generation outputs (required for async video generation)
# Bedrock video models (Luma Ray 2, Nova Reel) require an S3 bucket for output
# Default bucket created: bedrock-video-output-746780968188
BEDROCK_VIDEO_OUTPUT_BUCKET = os.getenv('BEDROCK_VIDEO_OUTPUT_BUCKET', 'bedrock-video-output-746780968188')
# Max seconds to wait for async video generation (polling). Default 600 (10 min). Increase if jobs often time out.
BEDROCK_VIDEO_GENERATION_TIMEOUT = int(os.getenv('BEDROCK_VIDEO_GENERATION_TIMEOUT', '600'))
# Path to ffmpeg for combine_video_audio (optional). If unset, uses PATH or /usr/bin/ffmpeg.
FFMPEG_PATH = os.getenv('FFMPEG_PATH', '').strip() or None
# If not set, the tools will attempt to auto-generate a bucket name based on AWS account ID
# Note: You must create the S3 bucket manually and ensure Bedrock has write permissions

# Ollama Configuration (fallback when AWS is not available)
# Set OLLAMA_ENABLED=false or leave OLLAMA_BASE_URL empty to disable all Ollama usage (no connection attempts)
OLLAMA_ENABLED = os.getenv('OLLAMA_ENABLED', 'true').lower() == 'true'
OLLAMA_BASE_URL = os.getenv('OLLAMA_BASE_URL', 'http://localhost:11434')
OLLAMA_DEFAULT_MODEL = os.getenv('OLLAMA_DEFAULT_MODEL', 'llama3.2:3b')
OLLAMA_EMBEDDING_MODEL = os.getenv('OLLAMA_EMBEDDING_MODEL', 'nomic-embed-text')
OLLAMA_TIMEOUT = int(os.getenv('OLLAMA_TIMEOUT', '180'))
OLLAMA_MAX_RETRIES = int(os.getenv('OLLAMA_MAX_RETRIES', '2'))
OLLAMA_VERIFY_SSL = os.getenv('OLLAMA_VERIFY_SSL', 'False').lower() == 'true'
# Production runtime tuning (passed to Ollama /api/chat and /api/generate)
OLLAMA_KEEP_ALIVE = os.getenv('OLLAMA_KEEP_ALIVE', '30m')
OLLAMA_NUM_CTX = int(os.getenv('OLLAMA_NUM_CTX', '8192'))
OLLAMA_NUM_PREDICT = int(os.getenv('OLLAMA_NUM_PREDICT', '4096'))
OLLAMA_TEMPERATURE = float(os.getenv('OLLAMA_TEMPERATURE', '0.7'))
OLLAMA_TOP_P = float(os.getenv('OLLAMA_TOP_P', '0.9'))
OLLAMA_TOP_K = int(os.getenv('OLLAMA_TOP_K', '40'))
OLLAMA_REPEAT_PENALTY = float(os.getenv('OLLAMA_REPEAT_PENALTY', '1.1'))
OLLAMA_NUM_THREAD = int(os.getenv('OLLAMA_NUM_THREAD', '0'))  # 0 = Ollama auto-detect
OLLAMA_NUM_BATCH = int(os.getenv('OLLAMA_NUM_BATCH', '1024'))
OLLAMA_WARMUP_ON_START = os.getenv('OLLAMA_WARMUP_ON_START', 'false').lower() == 'true'
OLLAMA_WARMUP_MODEL = os.getenv('OLLAMA_WARMUP_MODEL', OLLAMA_DEFAULT_MODEL)
try:
    import json as _json
    OLLAMA_MODEL_OPTIONS = _json.loads(os.getenv('OLLAMA_MODEL_OPTIONS', '{}'))
except (ValueError, TypeError):
    OLLAMA_MODEL_OPTIONS = {}
OLLAMA_MODEL_OPTIONS.setdefault('llama3.2:3b', {
    'num_ctx': OLLAMA_NUM_CTX,
    'num_predict': OLLAMA_NUM_PREDICT,
    'num_batch': OLLAMA_NUM_BATCH,
    'temperature': OLLAMA_TEMPERATURE,
    'top_p': OLLAMA_TOP_P,
    'top_k': OLLAMA_TOP_K,
    'repeat_penalty': OLLAMA_REPEAT_PENALTY,
})
OLLAMA_MODEL_OPTIONS.setdefault('llama3.1:70b', {
    'num_ctx': 4096,
    'num_predict': 2048,
    'num_batch': 512,
    'temperature': OLLAMA_TEMPERATURE,
    'top_p': OLLAMA_TOP_P,
    'top_k': OLLAMA_TOP_K,
    'repeat_penalty': OLLAMA_REPEAT_PENALTY,
})

# RAG Vector Store Configuration
RAG_VECTOR_STORE_BACKEND = os.getenv('RAG_VECTOR_STORE_BACKEND', 'qdrant')  # 'memory' or 'qdrant' (default: qdrant)
QDRANT_URL = os.getenv('QDRANT_URL', 'http://localhost:6333')
QDRANT_API_KEY = os.getenv('QDRANT_API_KEY', None)  # Optional, for cloud Qdrant

# Notification Configuration
SEND_RAG_NOTIFICATIONS = os.getenv('SEND_RAG_NOTIFICATIONS', 'False').lower() == 'true'  # Enable email notifications
DEFAULT_FROM_EMAIL = os.getenv('DEFAULT_FROM_EMAIL', 'support@oshaani.com')

# Site URL for generating absolute URLs in emails and notifications
# Default to oshaani.com (backend domain) - can be overridden via environment variable
SITE_URL = os.getenv('SITE_URL', 'https://oshaani.com')
SITE_NAME = os.getenv('SITE_NAME', 'Oshaani')

# Blog: send email to all users when a post is published (Celery, respects SES rate limits)
SEND_BLOG_NOTIFICATION_EMAILS = os.getenv('SEND_BLOG_NOTIFICATION_EMAILS', 'True').lower() == 'true'
BLOG_NOTIFICATION_BATCH_SIZE = int(os.getenv('BLOG_NOTIFICATION_BATCH_SIZE', '14'))  # SES ~14/sec
BLOG_NOTIFICATION_DELAY_SECONDS = float(os.getenv('BLOG_NOTIFICATION_DELAY_SECONDS', '1.0'))

# Email Configuration
# SMTP settings (used first, falls back to AWS SES if SMTP fails)
EMAIL_BACKEND = os.getenv('EMAIL_BACKEND', 'django.core.mail.backends.smtp.EmailBackend')
EMAIL_HOST = os.getenv('EMAIL_HOST', 'localhost')
EMAIL_PORT = int(os.getenv('EMAIL_PORT', '587'))
EMAIL_USE_TLS = os.getenv('EMAIL_USE_TLS', 'True').lower() == 'true'
EMAIL_USE_SSL = os.getenv('EMAIL_USE_SSL', 'False').lower() == 'true'
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD', '')

# AWS SES Configuration (fallback when SMTP is not available)
AWS_SES_REGION = os.getenv('AWS_SES_REGION', os.getenv('AWS_REGION', 'us-east-1'))
AWS_SES_CONFIGURATION_SET = os.getenv('AWS_SES_CONFIGURATION_SET', None)  # Optional SES configuration set

# File upload settings
FILE_UPLOAD_MAX_MEMORY_SIZE = 10 * 1024 * 1024  # 10MB
DATA_UPLOAD_MAX_MEMORY_SIZE = 10 * 1024 * 1024  # 10MB

# Login URLs
LOGIN_URL = '/'
LOGIN_REDIRECT_URL = '/dashboard/'
LOGOUT_REDIRECT_URL = '/'

# Authentication Configuration
AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
]

# Site ID
SITE_ID = 1

# LinkedIn OAuth Settings (using custom implementation)
# LinkedIn has migrated to OpenID Connect (OIDC) scopes
# OIDC scopes: openid, profile, email
LINKEDIN_CLIENT_ID = os.getenv('LINKEDIN_CLIENT_ID', '')
LINKEDIN_CLIENT_SECRET = os.getenv('LINKEDIN_CLIENT_SECRET', '')

# Celery Configuration
CELERY_BROKER_URL = os.getenv('CELERY_BROKER_URL', 'redis://localhost:6379/0')
CELERY_RESULT_BACKEND = os.getenv('CELERY_RESULT_BACKEND', 'redis://localhost:6379/0')
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = TIME_ZONE

# Channels Configuration
ASGI_APPLICATION = 'oshani.asgi.application'
_channel_redis_url = os.getenv('CHANNEL_REDIS_URL', 'redis://redis:6379/2')
_channel_socket_timeout_raw = os.getenv('CHANNEL_REDIS_SOCKET_TIMEOUT', 'none')
if _channel_socket_timeout_raw.lower() in ('', 'none', 'null'):
    # Blocking BZPOPMIN in channels-redis needs no socket read timeout (default breaks WS chat).
    _channel_socket_timeout = None
else:
    _channel_socket_timeout = int(_channel_socket_timeout_raw)

if _channel_redis_url:
    _channel_hosts = [{
        'address': _channel_redis_url,
        'socket_timeout': _channel_socket_timeout,
        'socket_connect_timeout': int(os.getenv('CHANNEL_REDIS_CONNECT_TIMEOUT', '10')),
    }]
else:
    _channel_hosts = [{
        'host': os.getenv('REDIS_HOST', '127.0.0.1'),
        'port': int(os.getenv('REDIS_PORT', '6379')),
        'socket_timeout': _channel_socket_timeout,
        'socket_connect_timeout': int(os.getenv('CHANNEL_REDIS_CONNECT_TIMEOUT', '10')),
    }]

CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels_redis.core.RedisChannelLayer',
        'CONFIG': {
            'hosts': _channel_hosts,
            'group_expiry': int(os.getenv('CHANNEL_GROUP_EXPIRY', '86400')),
        },
    },
}
# Celery Beat Schedule (for periodic tasks)
# Note: Model sync is on-demand only (manual trigger via API or management command)
# No automatic periodic tasks are scheduled

CELERY_BEAT_SCHEDULE = {
    # Model sync is available on-demand via:
    # - Management command: python3 manage.py sync_models
    # - API endpoint: POST /api/models/sync/
    
    # Periodic connector validation (every 6 hours)
    'validate-connectors': {
        'task': 'connectors.tasks.validate_all_connectors',
        'schedule': 21600.0,  # 6 hours
    },
    
    # Cleanup old conversations without messages (daily at 2 AM)
    'cleanup-old-conversations': {
        'task': 'agents_app.tasks.cleanup_old_conversations',
        'schedule': 86400.0,  # 24 hours (daily)
    },
    
    # - Dashboard: Click "Sync now" link
}

# Logging Configuration
# Create logs directory if it doesn't exist
LOGS_DIR = BASE_DIR / 'logs'
LOGS_DIR.mkdir(exist_ok=True)

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
            'datefmt': '%Y-%m-%d %H:%M:%S',
        },
        'simple': {
            'format': '{levelname} {asctime} {message}',
            'style': '{',
            'datefmt': '%Y-%m-%d %H:%M:%S',
        },
        'json': {
            'format': '{"timestamp": "%(asctime)s", "level": "%(levelname)s", "logger": "%(name)s", "module": "%(module)s", "message": "%(message)s", "pathname": "%(pathname)s", "lineno": %(lineno)d}',
            'datefmt': '%Y-%m-%d %H:%M:%S',
        },
    },
    'filters': {
        'require_debug_true': {
            '()': 'django.utils.log.RequireDebugTrue',
        },
        'require_debug_false': {
            '()': 'django.utils.log.RequireDebugFalse',
        },
    },
    'handlers': {
        'console': {
            'level': 'DEBUG' if DEBUG else 'INFO',
            'class': 'logging.StreamHandler',
            'formatter': 'simple',
            'filters': ['require_debug_true'],
        },
        'file': {
            'level': 'INFO',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': LOGS_DIR / 'django.log',
            'maxBytes': 10 * 1024 * 1024,  # 10 MB
            'backupCount': 5,
            'formatter': 'verbose',
        },
        'error_file': {
            'level': 'ERROR',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': LOGS_DIR / 'django_errors.log',
            'maxBytes': 10 * 1024 * 1024,  # 10 MB
            'backupCount': 10,
            'formatter': 'verbose',
        },
        'agents_file': {
            'level': 'INFO',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': LOGS_DIR / 'agents.log',
            'maxBytes': 10 * 1024 * 1024,  # 10 MB
            'backupCount': 5,
            'formatter': 'verbose',
        },
        'aws_file': {
            'level': 'INFO',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': LOGS_DIR / 'aws.log',
            'maxBytes': 10 * 1024 * 1024,  # 10 MB
            'backupCount': 5,
            'formatter': 'verbose',
        },
        'celery_file': {
            'level': 'INFO',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': LOGS_DIR / 'celery.log',
            'maxBytes': 10 * 1024 * 1024,  # 10 MB
            'backupCount': 5,
            'formatter': 'verbose',
        },
    },
    'loggers': {
        'django': {
            'handlers': ['console', 'file', 'error_file'],
            'level': 'INFO',
            'propagate': False,
        },
        'django.request': {
            'handlers': ['error_file', 'file'],
            'level': 'ERROR',
            'propagate': False,
        },
        'django.server': {
            'handlers': ['console', 'file'],
            'level': 'INFO',
            'propagate': False,
        },
        'django.db.backends': {
            'handlers': ['file'],
            'level': 'WARNING',  # Set to DEBUG to see SQL queries
            'propagate': False,
        },
        'agents_app': {
            'handlers': ['console', 'agents_file', 'error_file'],
            'level': 'DEBUG' if DEBUG else 'INFO',
            'propagate': False,
        },
        'agents_app.aws_integration': {
            'handlers': ['console', 'aws_file', 'error_file'],
            'level': 'DEBUG' if DEBUG else 'INFO',
            'propagate': False,
        },
        'agents_app.tasks': {
            'handlers': ['console', 'celery_file', 'error_file'],
            'level': 'DEBUG' if DEBUG else 'INFO',
            'propagate': False,
        },
        'celery': {
            'handlers': ['console', 'celery_file', 'error_file'],
            'level': 'INFO',
            'propagate': False,
        },
        'boto3': {
            'handlers': ['aws_file'],
            'level': 'WARNING',  # Reduce boto3 verbosity
            'propagate': False,
        },
        'botocore': {
            'handlers': ['aws_file'],
            'level': 'WARNING',  # Reduce botocore verbosity
            'propagate': False,
        },
        'urllib3': {
            'handlers': ['file'],
            'level': 'WARNING',  # Reduce urllib3 verbosity
            'propagate': False,
        },
    },
    'root': {
        'handlers': ['console', 'file', 'error_file'],
        'level': 'INFO',
    },
}
