# Generated by Django 4.2.27 on 2025-12-11 09:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('agent_type', models.CharField(choices=[('quick_sight', 'Quick Sight'), ('quick_flows', 'Quick Flows'), ('quick_automate', 'Quick Automate'), ('quick_research', 'Quick Research'), ('quick_index', 'Quick Index')], default='quick_sight', max_length=50)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('training', 'Training'), ('testing', 'Testing'), ('published', 'Published')], default='draft', max_length=20)),
                ('configuration', models.JSONField(blank=True, default=dict)),
                ('api_key', models.CharField(blank=True, db_index=True, max_length=255, null=True, unique=True)),
                ('api_key_hash', models.CharField(blank=True, max_length=64, null=True)),
                ('quick_suite_space_id', models.CharField(blank=True, max_length=255, null=True)),
                ('quick_suite_agent_id', models.CharField(blank=True, max_length=255, null=True)),
                ('training_data_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TrainingData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_type', models.CharField(choices=[('text', 'Text'), ('knowledge_base', 'Knowledge Base'), ('structured', 'Structured Data'), ('file', 'File Upload')], default='text', max_length=50)),
                ('content', models.JSONField(blank=True, default=dict)),
                ('file_path', models.FileField(blank=True, null=True, upload_to='training_data/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_data', to='agents_app.agent')),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='TestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_query', models.TextField()),
                ('expected_response', models.TextField(blank=True)),
                ('actual_response', models.TextField(blank=True)),
                ('score', models.FloatField(blank=True, null=True)),
                ('passed', models.BooleanField(default=False)),
                ('tested_at', models.DateTimeField(auto_now_add=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_results', to='agents_app.agent')),
            ],
            options={
                'ordering': ['-tested_at'],
            },
        ),
    ]
