# Generated by Django 4.2.27 on 2025-12-11 11:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agents_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_id', models.CharField(db_index=True, max_length=255, unique=True)),
                ('model_name', models.CharField(max_length=255)),
                ('provider', models.CharField(choices=[('bedrock', 'Amazon Bedrock'), ('ollama', 'Ollama')], max_length=50)),
                ('description', models.TextField(blank=True)),
                ('input_modalities', models.JSONField(blank=True, default=list)),
                ('output_modalities', models.JSONField(blank=True, default=list)),
                ('is_available', models.BooleanField(default=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('last_checked', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['provider', 'model_name'],
                'unique_together': {('model_id', 'provider')},
            },
        ),
        migrations.AddField(
            model_name='agent',
            name='model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agents', to='agents_app.aimodel'),
        ),
    ]
