# Generated by Django 4.2.27 on 2025-12-11 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents_app', '0002_aimodel_agent_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='aimodel',
            name='use_cases',
            field=models.JSONField(blank=True, default=list, help_text='Best use cases for this model'),
        ),
    ]
