# Generated by Django 4.2.27 on 2025-12-11 14:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('agents_app', '0003_add_use_cases_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.TextField(help_text="The user's query")),
                ('response', models.TextField(help_text="The agent's response")),
                ('feedback_type', models.CharField(choices=[('positive', 'Positive (Helpful)'), ('negative', 'Negative (Not Helpful)'), ('neutral', 'Neutral')], max_length=20)),
                ('feedback_text', models.TextField(blank=True, help_text='Optional detailed feedback')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='agents_app.agent')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_feedbacks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['agent', 'feedback_type'], name='agents_app__agent_i_2cbd9b_idx'), models.Index(fields=['created_at'], name='agents_app__created_afdf29_idx')],
            },
        ),
    ]
