# Generated by Django 4.2.27 on 2025-12-11 14:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('agents_app', '0004_add_agent_feedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conversation_id', models.CharField(db_index=True, max_length=255, unique=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('archived', 'Archived')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='agents_app.agent')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ToolCall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tool_name', models.CharField(max_length=100)),
                ('parameters', models.JSONField(default=dict)),
                ('result_content', models.TextField(blank=True)),
                ('result_files', models.JSONField(blank=True, default=list)),
                ('error', models.TextField(blank=True)),
                ('state', models.CharField(choices=[('pending', 'Pending'), ('executing', 'Executing'), ('done', 'Done'), ('error', 'Error')], default='pending', max_length=20)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tool_calls', to='agents_app.agent')),
                ('conversation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tool_calls', to='agents_app.conversation')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ConversationMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_type', models.CharField(choices=[('user', 'User Message'), ('agent', 'Agent Message'), ('tool_call', 'Tool Call'), ('tool_result', 'Tool Result')], max_length=20)),
                ('content', models.TextField()),
                ('tool_name', models.CharField(blank=True, help_text='Tool name if message_type is tool_call or tool_result', max_length=100)),
                ('tool_parameters', models.JSONField(blank=True, default=dict)),
                ('tool_result', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='agents_app.conversation')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='CustomTool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(help_text='Name visible to users', max_length=200)),
                ('function_name', models.CharField(help_text='Function name visible to agent (lowercase, underscores)', max_length=100)),
                ('description', models.TextField(help_text='What the tool does')),
                ('instructions', models.TextField(blank=True, help_text='Additional instructions for the agent')),
                ('url', models.URLField(help_text='Tool endpoint URL')),
                ('method', models.CharField(choices=[('GET', 'GET'), ('POST', 'POST'), ('PUT', 'PUT'), ('DELETE', 'DELETE')], default='POST', max_length=10)),
                ('headers', models.JSONField(blank=True, default=dict, help_text='HTTP headers (e.g., for authentication)')),
                ('parameters', models.JSONField(blank=True, default=list, help_text='Tool parameters configuration')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_tools', to='agents_app.agent')),
            ],
            options={
                'ordering': ['display_name'],
                'unique_together': {('agent', 'function_name')},
            },
        ),
    ]
