# Generated by Django 4.2.27 on 2025-12-12 03:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agents_app', '0005_add_tools_and_conversations'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConversationFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255)),
                ('file_path', models.FileField(blank=True, null=True, upload_to='conversation_files/')),
                ('file_type', models.CharField(blank=True, max_length=100)),
                ('file_size', models.BigIntegerField(default=0)),
                ('file_id', models.CharField(db_index=True, max_length=255, unique=True)),
                ('upload_url', models.URLField(blank=True, help_text='Temporary upload URL')),
                ('download_url', models.URLField(blank=True, help_text='Temporary download URL')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversation_files', to='agents_app.agent')),
                ('conversation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='files', to='agents_app.conversation')),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='MCPServer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the MCP server', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Description of what this MCP server provides')),
                ('transport_type', models.CharField(choices=[('stdio', 'STDIO'), ('http', 'HTTP'), ('sse', 'SSE')], default='stdio', max_length=20)),
                ('command', models.CharField(blank=True, help_text="Command to run the MCP server (e.g., 'npx', 'uvx')", max_length=500)),
                ('args', models.JSONField(blank=True, default=list, help_text="Arguments for the command (e.g., ['-y', '@modelcontextprotocol/server-filesystem', '.'])")),
                ('url', models.URLField(blank=True, help_text='URL for HTTP/SSE transport')),
                ('headers', models.JSONField(blank=True, default=dict, help_text='HTTP headers for authentication')),
                ('is_active', models.BooleanField(default=True)),
                ('auto_connect', models.BooleanField(default=True, help_text='Automatically connect when agent is used')),
                ('configuration', models.JSONField(blank=True, default=dict, help_text='Additional configuration')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mcp_servers', to='agents_app.agent')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('agent', 'name')},
            },
        ),
    ]
