# Generated by Django 4.2.27 on 2025-12-12 03:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agents_app', '0006_conversationfile_mcpserver'),
    ]

    operations = [
        migrations.CreateModel(
            name='RAGIndexStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chunks_count', models.IntegerField(default=0, help_text='Number of chunks indexed')),
                ('indexed_at', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('embedding_provider', models.CharField(default='bedrock', help_text='Provider used for embeddings', max_length=50)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this index is active')),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rag_index_status', to='agents_app.agent')),
                ('training_data', models.ForeignKey(blank=True, help_text='Specific training data item indexed (null means all)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rag_index_status', to='agents_app.trainingdata')),
            ],
            options={
                'ordering': ['-indexed_at'],
                'unique_together': {('agent', 'training_data')},
            },
        ),
    ]
