# Generated by Django 4.2.27 on 2025-12-12 09:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('agents_app', '0009_add_user_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='InferenceProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_name', models.CharField(db_index=True, help_text='Unique name for the inference profile', max_length=255, unique=True)),
                ('profile_arn', models.CharField(blank=True, help_text='AWS ARN of the inference profile', max_length=500)),
                ('status', models.CharField(choices=[('creating', 'Creating'), ('active', 'Active'), ('updating', 'Updating'), ('deleting', 'Deleting'), ('failed', 'Failed')], default='creating', max_length=20)),
                ('regions', models.JSONField(default=list, help_text='List of AWS regions where inference requests can be routed')),
                ('configuration', models.JSONField(blank=True, default=dict, help_text='Additional inference profile configuration')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Metadata about the inference profile')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_used', models.DateTimeField(blank=True, help_text='Last time this inference profile was used', null=True)),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this inference profile', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inference_profiles', to=settings.AUTH_USER_MODEL)),
                ('model', models.ForeignKey(help_text='Model that requires this inference profile', on_delete=django.db.models.deletion.CASCADE, related_name='inference_profiles', to='agents_app.aimodel')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('model', 'profile_name')},
            },
        ),
        migrations.AddField(
            model_name='agent',
            name='inference_profile',
            field=models.ForeignKey(blank=True, help_text='Inference profile for models that require provisioning', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agents', to='agents_app.inferenceprofile'),
        ),
    ]
