# Generated by Django 4.2.27 on 2025-12-12 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents_app', '0011_userapikey'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userapikey',
            name='name',
            field=models.CharField(blank=True, help_text='Optional name/description for this key', max_length=100, null=True),
        ),
    ]
