# Generated by Django 4.2.27 on 2025-12-12 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents_app', '0012_add_null_to_userapikey_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='published_configuration',
            field=models.JSONField(blank=True, default=dict, help_text='Snapshot of configuration when last published', null=True),
        ),
        migrations.AddField(
            model_name='agent',
            name='published_training_data_count',
            field=models.IntegerField(default=0, help_text='Training data count when last published', null=True),
        ),
        migrations.AlterField(
            model_name='agent',
            name='agent_type',
            field=models.CharField(choices=[('quick_bot', 'Chat Bot'), ('quick_flows', 'Quick Flows'), ('quick_automate', 'Quick Automate'), ('quick_research', 'Quick Research'), ('quick_index', 'Quick Index')], default='quick_sight', max_length=50),
        ),
    ]
