# Generated by Django 4.2.27 on 2025-12-16 07:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agents_app', '0013_add_published_configuration_tracking'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_id', models.CharField(db_index=True, help_text='Unique request ID for polling', max_length=255, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('message', models.TextField(help_text='User message that triggered this request')),
                ('response', models.TextField(blank=True, help_text='Agent response (when completed)')),
                ('tool_calls', models.JSONField(blank=True, default=list, help_text='Tool calls made during processing')),
                ('iterations', models.IntegerField(default=0, help_text='Number of iterations')),
                ('error_message', models.TextField(blank=True, help_text='Error message if status is failed')),
                ('celery_task_id', models.CharField(blank=True, db_index=True, help_text='Celery task ID for tracking', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='agents_app.agent')),
                ('conversation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='agents_app.conversation')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['request_id'], name='agents_app__request_11b2c5_idx'), models.Index(fields=['status', 'created_at'], name='agents_app__status_146930_idx'), models.Index(fields=['celery_task_id'], name='agents_app__celery__a97a9a_idx')],
            },
        ),
    ]
