# Generated by Django 4.2.27 on 2025-12-17 14:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('agents_app', '0015_add_system_settings'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentShare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(help_text='Email address of the user to share with', max_length=254)),
                ('token', models.CharField(db_index=True, help_text='Unique token for accessing the shared agent', max_length=64, unique=True)),
                ('message', models.TextField(blank=True, help_text='Optional message from the sharer')),
                ('expires_at', models.DateTimeField(blank=True, help_text='Expiration date for the share (optional)', null=True)),
                ('is_accepted', models.BooleanField(default=False, help_text='Whether the share has been accepted')),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('accepted_by', models.ForeignKey(blank=True, help_text='User who accepted the share', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accepted_agent_shares', to=settings.AUTH_USER_MODEL)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shares', to='agents_app.agent')),
                ('shared_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_agents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['token'], name='agents_app__token_5a1127_idx'), models.Index(fields=['email', 'is_accepted'], name='agents_app__email_1917fb_idx')],
                'unique_together': {('agent', 'email')},
            },
        ),
    ]
