# Generated by Django 4.2.27 on 2025-12-25 19:17

from django.db import migrations, models


def update_quick_sight_to_chat_agent(apps, schema_editor):
    """Update existing agents with quick_sight to chat_agent."""
    Agent = apps.get_model('agents_app', 'Agent')
    Agent.objects.filter(agent_type='quick_sight').update(agent_type='chat_agent')


def reverse_update(apps, schema_editor):
    """Reverse migration: change chat_agent back to quick_sight."""
    Agent = apps.get_model('agents_app', 'Agent')
    Agent.objects.filter(agent_type='chat_agent').update(agent_type='quick_sight')


class Migration(migrations.Migration):

    dependencies = [
        ('agents_app', '0016_agentshare'),
    ]

    operations = [
        # Data migration: update existing agents
        migrations.RunPython(update_quick_sight_to_chat_agent, reverse_update),
        # Schema migration: update field choices and default
        migrations.AlterField(
            model_name='agent',
            name='agent_type',
            field=models.CharField(choices=[('chat_agent', 'Chat Agent'), ('quick_bot', 'Chat Bot'), ('quick_flows', 'Quick Flows'), ('quick_automate', 'Quick Automate'), ('quick_research', 'Quick Research'), ('quick_index', 'Quick Index')], default='chat_agent', max_length=50),
        ),
    ]
