# Generated by Django 4.2.27 on 2025-12-25 20:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('agents_app', '0017_rename_quick_sight_to_chat_agent'),
    ]

    operations = [
        migrations.CreateModel(
            name='SharedAgentUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_count', models.IntegerField(default=0, help_text='Number of messages sent')),
                ('conversation_count', models.IntegerField(default=0, help_text='Number of conversations')),
                ('last_used_at', models.DateTimeField(blank=True, help_text='Last time the agent was used', null=True)),
                ('first_used_at', models.DateTimeField(auto_now_add=True, help_text='First time the agent was used')),
                ('period_start', models.DateTimeField(help_text='Start of the usage period')),
                ('period_end', models.DateTimeField(help_text='End of the usage period')),
                ('is_daily', models.BooleanField(default=False, help_text='True for daily metrics, False for monthly')),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_usage', to='agents_app.agent')),
                ('share', models.ForeignKey(blank=True, help_text='The share record that granted access', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usage_records', to='agents_app.agentshare')),
                ('shared_by', models.ForeignKey(help_text='Owner of the agent', on_delete=django.db.models.deletion.CASCADE, related_name='shared_agent_usage', to=settings.AUTH_USER_MODEL)),
                ('used_by', models.ForeignKey(help_text='User who is using the shared agent', on_delete=django.db.models.deletion.CASCADE, related_name='used_shared_agents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Shared Agent Usage',
                'verbose_name_plural': 'Shared Agent Usage Records',
                'ordering': ['-last_used_at', '-first_used_at'],
                'indexes': [models.Index(fields=['agent', 'used_by', 'period_start'], name='agents_app__agent_i_5940fd_idx'), models.Index(fields=['shared_by', 'period_start'], name='agents_app__shared__c5a1f4_idx'), models.Index(fields=['agent', 'last_used_at'], name='agents_app__agent_i_5c96c5_idx')],
                'unique_together': {('agent', 'used_by', 'period_start', 'is_daily')},
            },
        ),
    ]
