# Generated by Django 4.2.27 on 2025-12-25 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agents_app', '0018_add_shared_agent_usage'),
    ]

    operations = [
        migrations.RunSQL(
            # Convert content column to utf8mb4
            sql="ALTER TABLE `agents_app_conversationmessage` MODIFY COLUMN `content` TEXT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL;",
            reverse_sql="ALTER TABLE `agents_app_conversationmessage` MODIFY COLUMN `content` TEXT CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL;",
        ),
    ]
