# Generated by Django 4.2.27 on 2025-12-28 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agents_app', '0019_fix_conversationmessage_utf8mb4'),
    ]

    operations = [
        migrations.RunSQL(
            # Convert result_content column to utf8mb4
            sql="ALTER TABLE `agents_app_toolcall` MODIFY COLUMN `result_content` TEXT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL;",
            reverse_sql="ALTER TABLE `agents_app_toolcall` MODIFY COLUMN `result_content` TEXT CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL;",
        ),
        migrations.RunSQL(
            # Convert error column to utf8mb4 (also a TextField that might contain emojis)
            sql="ALTER TABLE `agents_app_toolcall` MODIFY COLUMN `error` TEXT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL;",
            reverse_sql="ALTER TABLE `agents_app_toolcall` MODIFY COLUMN `error` TEXT CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL;",
        ),
    ]
