# Generated by Django 4.2.27 on 2025-12-28 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agents_app', '0020_fix_toolcall_utf8mb4'),
    ]

    operations = [
        migrations.RunSQL(
            # Convert query column to utf8mb4
            sql="ALTER TABLE `agents_app_agentfeedback` MODIFY COLUMN `query` TEXT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL;",
            reverse_sql="ALTER TABLE `agents_app_agentfeedback` MODIFY COLUMN `query` TEXT CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL;",
        ),
        migrations.RunSQL(
            # Convert response column to utf8mb4
            sql="ALTER TABLE `agents_app_agentfeedback` MODIFY COLUMN `response` TEXT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL;",
            reverse_sql="ALTER TABLE `agents_app_agentfeedback` MODIFY COLUMN `response` TEXT CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL;",
        ),
        migrations.RunSQL(
            # Convert feedback_text column to utf8mb4 (nullable field)
            sql="ALTER TABLE `agents_app_agentfeedback` MODIFY COLUMN `feedback_text` TEXT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL;",
            reverse_sql="ALTER TABLE `agents_app_agentfeedback` MODIFY COLUMN `feedback_text` TEXT CHARACTER SET utf8 COLLATE utf8_general_ci NULL;",
        ),
    ]

