# Generated by Django 4.2.27 on 2025-12-30 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agents_app', '0022_add_agentpublicshare'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='agentpublicshare',
            new_name='agents_app__token_7b1405_idx',
            old_name='agents_app__token_public_idx',
        ),
        migrations.RenameIndex(
            model_name='agentpublicshare',
            new_name='agents_app__agent_i_de6598_idx',
            old_name='agents_app__agent_public_idx',
        ),
    ]
