# Generated by Django 4.2.27 on 2026-01-07 11:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('agents_app', '0023_rename_agents_app__token_public_idx_agents_app__token_7b1405_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback_type', models.CharField(choices=[('like', 'Like'), ('dislike', 'Dislike')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='agents_app.agent')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_likes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['agent', 'feedback_type'], name='agents_app__agent_i_d714b1_idx'), models.Index(fields=['agent', 'user'], name='agents_app__agent_i_c5fefb_idx')],
                'unique_together': {('agent', 'user')},
            },
        ),
    ]
