# Generated by Django 4.2.27 on 2026-01-08 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents_app', '0024_add_agent_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='onboarding_tour_completed',
            field=models.BooleanField(default=False, help_text='Whether user has completed the onboarding tour'),
        ),
    ]
