# Generated by Django 4.2.27 on 2026-02-03 17:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agents_app', '0028_add_agent_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentTool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tool_name', models.CharField(help_text='Name of the tool', max_length=100)),
                ('is_enabled', models.BooleanField(default=True, help_text='Whether the tool is enabled for this agent')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_tools', to='agents_app.agent')),
            ],
            options={
                'ordering': ['tool_name'],
                'indexes': [models.Index(fields=['agent', 'is_enabled'], name='agents_app__agent_i_ba8c91_idx')],
                'unique_together': {('agent', 'tool_name')},
            },
        ),
    ]
