# Generated by Django 4.2.27 on 2026-02-03 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents_app', '0029_add_agent_tool_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='privacy_accepted',
            field=models.BooleanField(default=False, help_text='Whether user has accepted privacy policy'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='privacy_accepted_at',
            field=models.DateTimeField(blank=True, help_text='When user accepted privacy policy', null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='terms_accepted',
            field=models.BooleanField(default=False, help_text='Whether user has accepted terms & conditions'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='terms_accepted_at',
            field=models.DateTimeField(blank=True, help_text='When user accepted terms', null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='mobile_number',
            field=models.CharField(blank=True, help_text="User's mobile number", max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, help_text="User's profile picture", null=True, upload_to='profile_pictures/'),
        ),
    ]
