# Generated by Django 4.2.27 on 2026-02-18 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents_app', '0030_userprofile_privacy_accepted_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Display name (e.g. Twitter, LinkedIn)', max_length=100)),
                ('url', models.URLField(help_text='Full URL to your profile or page', max_length=500)),
                ('platform', models.CharField(choices=[('twitter', 'Twitter / X'), ('linkedin', 'LinkedIn'), ('facebook', 'Facebook'), ('youtube', 'YouTube'), ('instagram', 'Instagram'), ('github', 'GitHub'), ('other', 'Other')], default='other', help_text='Platform for icon (Bootstrap Icons: bi-twitter, bi-linkedin, etc.)', max_length=20)),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order (lower first)')),
                ('is_active', models.BooleanField(default=True, help_text='Show this link in the footer')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Social Link',
                'verbose_name_plural': 'Social Links',
                'ordering': ['order', 'name'],
            },
        ),
    ]
