# Generated by Django 4.2.27 on 2026-04-28 10:51

from django.db import migrations, models
import django.db.models.deletion


def migrate_agent_api_key_hashes(apps, schema_editor):
    Agent = apps.get_model('agents_app', 'Agent')
    AgentAPIKey = apps.get_model('agents_app', 'AgentAPIKey')
    for agent in Agent.objects.exclude(api_key_hash__isnull=True).exclude(api_key_hash=''):
        if AgentAPIKey.objects.filter(agent_id=agent.pk).exists():
            continue
        AgentAPIKey.objects.create(
            agent_id=agent.pk,
            name='Primary (migrated)',
            api_key_hash=agent.api_key_hash,
            is_active=True,
        )


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('agents_app', '0031_add_social_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentAPIKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='Optional label (e.g. production, CI, partner)', max_length=100, null=True)),
                ('api_key_hash', models.CharField(blank=True, db_index=True, max_length=64, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_used', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_api_keys', to='agents_app.agent')),
            ],
            options={
                'verbose_name': 'Agent API Key',
                'verbose_name_plural': 'Agent API Keys',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['api_key_hash', 'is_active'], name='agents_app__api_key_4e0826_idx'), models.Index(fields=['agent', 'is_active'], name='agents_app__agent_i_f09b7d_idx')],
            },
        ),
        migrations.RunPython(migrate_agent_api_key_hashes, noop_reverse),
    ]
