# Generated by Django 4.2.27 on 2026-02-11 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='video',
            field=models.FileField(blank=True, help_text='Optional video file for the post (e.g. MP4)', null=True, upload_to='blog/videos/'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='video_url',
            field=models.URLField(blank=True, help_text='Optional embed URL (YouTube, Vimeo, etc.). Used if no video file is uploaded.'),
        ),
    ]
