# Generated by Django 4.2.27 on 2026-02-11 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0002_add_video_to_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='video_url',
            field=models.URLField(blank=True, default='', help_text='Optional embed URL (YouTube, Vimeo, etc.). Used if no video file is uploaded.'),
        ),
    ]
