# Generated by Django 4.2.27 on 2026-02-11 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0003_video_url_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='notification_sent',
            field=models.BooleanField(default=False, editable=False, help_text='Whether notification email was sent to users for this post'),
        ),
    ]
