# Generated by Django 4.2.27 on 2025-12-16 18:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agents_app', '0014_add_agent_request_model'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Connector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Friendly name for this connector', max_length=200)),
                ('connector_type', models.CharField(choices=[('jira', 'JIRA'), ('confluence', 'Confluence'), ('slack', 'Slack'), ('github', 'GitHub')], max_length=50)),
                ('status', models.CharField(choices=[('disconnected', 'Disconnected'), ('connecting', 'Connecting'), ('connected', 'Connected'), ('error', 'Error')], default='disconnected', max_length=20)),
                ('client_id', models.CharField(blank=True, help_text='OAuth Client ID', max_length=255)),
                ('client_secret', models.CharField(blank=True, help_text='OAuth Client Secret', max_length=255)),
                ('access_token', models.TextField(blank=True, help_text='OAuth Access Token')),
                ('refresh_token', models.TextField(blank=True, help_text='OAuth Refresh Token')),
                ('token_expires_at', models.DateTimeField(blank=True, help_text='Token expiration time', null=True)),
                ('base_url', models.URLField(help_text='Base URL of the service (e.g., https://your-domain.atlassian.net)')),
                ('site_url', models.URLField(blank=True, help_text='Site URL for OAuth callback')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional connector metadata')),
                ('configuration', models.JSONField(blank=True, default=dict, help_text='Connector-specific configuration')),
                ('connected_at', models.DateTimeField(blank=True, null=True)),
                ('last_sync_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connectors', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('user', 'connector_type', 'base_url')},
            },
        ),
        migrations.CreateModel(
            name='ConnectorSync',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('sync_type', models.CharField(help_text="Type of sync (e.g., 'jira_issues', 'confluence_pages')", max_length=50)),
                ('items_synced', models.IntegerField(default=0)),
                ('items_failed', models.IntegerField(default=0)),
                ('result_data', models.JSONField(blank=True, default=dict, help_text='Sync result details')),
                ('error_message', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='connector_syncs', to='agents_app.agent')),
                ('connector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='syncs', to='connectors.connector')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
