# Generated by Django 4.2.27 on 2025-12-16 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connectors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connector',
            name='connector_type',
            field=models.CharField(choices=[('jira', 'JIRA'), ('confluence', 'Confluence'), ('gitlab', 'GitLab'), ('slack', 'Slack'), ('github', 'GitHub')], max_length=50),
        ),
    ]
