# Generated by Django 4.2.27 on 2025-12-17 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connectors', '0002_alter_connector_connector_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connector',
            name='connector_type',
            field=models.CharField(choices=[('jira', 'JIRA'), ('confluence', 'Confluence'), ('gitlab', 'GitLab'), ('slack', 'Slack'), ('github', 'GitHub'), ('google', 'Google'), ('microsoft', 'Microsoft')], max_length=50),
        ),
    ]
