# Generated by Django 4.2.27 on 2026-01-07 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connectors', '0003_alter_connector_connector_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connector',
            name='connector_type',
            field=models.CharField(choices=[('jira', 'JIRA'), ('confluence', 'Confluence'), ('gitlab', 'GitLab'), ('slack', 'Slack'), ('github', 'GitHub'), ('google', 'Google'), ('microsoft', 'Microsoft'), ('linkedin', 'LinkedIn'), ('facebook', 'Facebook'), ('instagram', 'Instagram'), ('twitter', 'Twitter')], max_length=50),
        ),
    ]
