# Generated by Django 4.2.27 on 2026-01-08 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connectors', '0004_add_social_media_connectors'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialMediaOAuthConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('linkedin', 'LinkedIn'), ('facebook', 'Facebook'), ('twitter', 'Twitter/X'), ('instagram', 'Instagram'), ('google', 'Google')], help_text='Social media platform', max_length=50, unique=True)),
                ('client_id', models.CharField(help_text='OAuth Client ID (managed by admin)', max_length=255)),
                ('client_secret', models.CharField(help_text='OAuth Client Secret (managed by admin)', max_length=255)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this OAuth config is active')),
                ('redirect_uri_base', models.URLField(blank=True, help_text='Base redirect URI (will be appended with platform-specific path)')),
                ('scopes', models.TextField(blank=True, help_text='Comma-separated list of OAuth scopes')),
                ('notes', models.TextField(blank=True, help_text='Admin notes about this OAuth configuration')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Social Media OAuth Configuration',
                'verbose_name_plural': 'Social Media OAuth Configurations',
                'ordering': ['platform'],
            },
        ),
    ]
