# Generated by Django 4.2.27 on 2026-02-03 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connectors', '0005_socialmediaoauthconfig'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connector',
            name='connector_type',
            field=models.CharField(choices=[('jira', 'JIRA'), ('confluence', 'Confluence'), ('gitlab', 'GitLab'), ('slack', 'Slack'), ('github', 'GitHub'), ('google', 'Google'), ('microsoft', 'Microsoft'), ('linkedin', 'LinkedIn'), ('facebook', 'Facebook'), ('instagram', 'Instagram'), ('twitter', 'X')], max_length=50),
        ),
        migrations.AlterField(
            model_name='socialmediaoauthconfig',
            name='platform',
            field=models.CharField(choices=[('linkedin', 'LinkedIn'), ('facebook', 'Facebook'), ('twitter', 'X'), ('instagram', 'Instagram'), ('google', 'Google')], help_text='Social media platform', max_length=50, unique=True),
        ),
    ]
